# config/packages/nelmio_cors.yaml

nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%'] # Usaremos una variable de entorno
        allow_headers: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        # Aplica estas reglas a todas las rutas de la API
        '^/api/':
            # Permite el tráfico. Los encabezados específicos se definen arriba